------------------------------------------------
-- This file is part of Decision Descent.
--
-- Decision Descent is free software:
-- you can redistribute it
-- and/or modify it under the
-- terms of the GNU General
-- Public License as published by
-- the Free Software Foundation,
-- either version 3 of the License,
-- or (at your option) any later
-- version.
--
-- Decision Descent is distributed in
-- the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without
-- even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A
-- PARTICULAR PURPOSE.  See the GNU
-- General Public License for more details.
--
-- You should have received a copy of the
-- GNU General Public License along with
-- Decision Descent.  If not,
-- see <https://www.gnu.org/licenses/>.
------------------------------------------------

-- While you can modify this file directly,
-- these values are overwritten externally
-- by the brain upon sync.  This file purely
-- exists for type hints.  The only real
-- values you can change are the HTTP settings.

---@field minimum number  @The minimum number of rooms in a given room type that may have an item poll.  This number is generally the total number of vanilla rooms that would generate with an item.
---@field maximum number  @The maximum number of rooms in a given room type that may have an item poll.  This number is generally the total number of room variants this room type would have in base game.
---@field devil number  @The number of rooms in a given room type that may have a devil item.  This number is generally the amount of item rooms that would generate with a devil item.  This value should generally be lower than `MINIMUM`
---@class RoomDef
local RoomDef = {}

---@field revive boolean  @Whether or not an item would revive the player should it be awarded.  In older versions of the mod, a poll would never award such items if the player couldn't afford the price in hearts, so this workaround was made.
---@class ItemDef
local ItemDef = {}

return {
    http = {
        ---
        --- The host address to connect to.
        ---
        ---@type string
        host = "127.0.0.1",
    
        ---
        --- The port to connect to.
        ---
        ---@type number
        port = 25565
    },
    
    rng = {
        --- Room RNG settings pertaining to the frequency of polls when these
        --- rooms are encountered.  These values accurate representations of the
        --- chances the player has of encouraging an item in said room.
        ---
        ---@type table<string, RoomDef>
        rooms = {
            [tostring(RoomType.ROOM_ERROR)] = {
                minimum = 7,
                maximum = 28,
                devil = 3
            },
        
            [tostring(RoomType.ROOM_CURSE)] = {
                minimum = 2,
                maximum = 25
            }
        },
    
        ---
        --- Item RNG settings pertaining to metadata bout certain items that
        --- can't be reliably retrieved from base game.
        ---
        ---@type table<string, ItemDef>
        items = {
            [tostring(CollectibleType.COLLECTIBLE_DEAD_CAT)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_ONE_UP)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_JUDAS_SHADOW)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_LAZARUS_RAGS)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_ANKH)] = {
                revive = true
            }
        }
    },

    ---
    --- Poll settings relate to polls generated by this half.
    ---
    polls = {
        ---
        --- Choice settings affects choices in generated polls.
        ---
        choices = {
            ---
            --- The maximum number of choices that can in a given poll.  Polls
            --- are permitted to exceed this limit if special choices are present,
            --- but standard choices will adhere to this setting.
            ---
            ---@type number
            maximum = 3
        },
    
        ---
        --- The number of seconds a default poll will be active before tallying
        --- the results.
        ---
        ---@type number
        duration = 35
    },
    
    hud = {
        ---
        --- Whether or not the hud is enabled.  This hud is a "small" overlay
        --- that displays information about the mod, and an on-screen poll.
        ---
        ---@type boolean
        enabled = true
    }
}
