------------------------------------------------
-- This file is part of Decision Descent.
--
-- Decision Descent is free software:
-- you can redistribute it
-- and/or modify it under the
-- terms of the GNU General
-- Public License as published by
-- the Free Software Foundation,
-- either version 3 of the License,
-- or (at your option) any later
-- version.
--
-- Decision Descent is distributed in
-- the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without
-- even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A
-- PARTICULAR PURPOSE.  See the GNU
-- General Public License for more details.
--
-- You should have received a copy of the
-- GNU General Public License along with
-- Decision Descent.  If not,
-- see <https://www.gnu.org/licenses/>.
------------------------------------------------

-- While you can modify this file directly,
-- these values are overwritten externally
-- by the brain upon sync.  This file purely
-- exists for type hints.  The only real
-- values you can change are the HTTP settings.

return {
    http = {
        -- The host address to connect to.
        --
        -- TYPE    » STRING
        -- DEFAULT » 127.0.0.1
        host = "127.0.0.1",
        
        -- The port to connect to.
        --
        -- TYPE    » INTEGER
        -- DEFAULT » 25565
        port = 25565
    },
    
    rng = {
        rooms = {
            -- Room RNG settings pertain to the frequency of polls
            -- when these rooms are encountered.  These values are
            -- accurate representations of the chances the player
            -- has of encountering an item in said room.
            --
            -- MINIMUM (INTEGER)   » The minimum number of rooms in a
            --                       given room type that may have an
            --                       item poll.  This number is generally
            --                       the total number of vanilla rooms
            --                       that would generate with an item.
            -- MAXIMUM (INTEGER)   » The maximum number of rooms in a
            --                       given room type.  This number is
            --                       generally the total number of room
            --                       variants this room type would have
            --                       in base game.
            -- DEVIL   (INTEGER)   » The number of rooms in a given room
            --                       type that may have a devil item.
            --                       This number is generally the amount
            --                       of item rooms that would generate
            --                       with a devil item.  This value should
            --                       generally be lower than `MINIMUM`.
            [tostring(RoomType.ROOM_ERROR)] = {
                minimum = 7,
                maximum = 28,
                devil = 3
            },
            
            [tostring(RoomType.ROOM_CURSE)] = {
                minimum = 2,
                maximum = 25
            }
        },
        
        items = {
            -- Item RNG settings pertain to metadata about certain
            -- items that can't be reliably retrieved from base game.
            --
            -- Current values are...
            -- REVIVE  (BOOLEAN)   » Whether or not an item would revive
            --                       the player should it be awarded.
            --                       In older versions of the mod, a poll
            --                       would never award such items if the
            --                       player couldn't afford the price in
            --                       hearts, so this workaround was made.
            [tostring(CollectibleType.COLLECTIBLE_DEAD_CAT)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_ONE_UP)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_JUDAS_SHADOW)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_LAZARUS_RAGS)] = {
                revive = true
            },
            [tostring(CollectibleType.COLLECTIBLE_ANKH)] = {
                revive = true
            }
        }
    },
    
    -- Poll settings relate to polls generated by this half.
    polls = {
        -- Choice settings affect choices in generated polls.
        --
        -- MAXIMUM  (NUMBER)  » The maximum number of choices that can be in a
        --                      given poll.  Polls are permitted to exceed this
        --                      limit if special choices are present, but
        --                      standard choices will adhere to this setting.
        choices = {
            maximum = 3
        },
        
        -- DURATION (NUMBER)  » The number of seconds a default poll will be
        --                      active before tallying the results.
        duration = 35
    },
    
    hud = {
        -- Whether or not the hud is enabled.  The hud is a "small" overlay
        -- that displays information about the mod, and an on-screen poll.
        enabled = true
    }
}
