# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ClientApp(object):
    def setupUi(self, ClientApp):
        ClientApp.setObjectName("ClientApp")
        ClientApp.resize(571, 407)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../assets/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ClientApp.setWindowIcon(icon)
        ClientApp.setDocumentMode(True)
        self.app_central = QtWidgets.QWidget(ClientApp)
        self.app_central.setObjectName("app_central")
        self.app_layout = QtWidgets.QGridLayout(self.app_central)
        self.app_layout.setContentsMargins(0, 0, 0, 0)
        self.app_layout.setSpacing(6)
        self.app_layout.setObjectName("app_layout")
        self.log_tabs = QtWidgets.QTabWidget(self.app_central)
        self.log_tabs.setTabPosition(QtWidgets.QTabWidget.West)
        self.log_tabs.setObjectName("log_tabs")
        self.client_log_tab = QtWidgets.QWidget()
        self.client_log_tab.setObjectName("client_log_tab")
        self.client_log_layout = QtWidgets.QGridLayout(self.client_log_tab)
        self.client_log_layout.setContentsMargins(11, 11, 11, 11)
        self.client_log_layout.setSpacing(6)
        self.client_log_layout.setObjectName("client_log_layout")
        self.client_filter_label = QtWidgets.QLabel(self.client_log_tab)
        self.client_filter_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.client_filter_label.setWordWrap(True)
        self.client_filter_label.setObjectName("client_filter_label")
        self.client_log_layout.addWidget(self.client_filter_label, 0, 0, 1, 1)
        self.client_filter = QtWidgets.QComboBox(self.client_log_tab)
        self.client_filter.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.client_filter.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.client_filter.setObjectName("client_filter")
        self.client_filter.addItem("")
        self.client_filter.addItem("")
        self.client_filter.addItem("")
        self.client_filter.addItem("")
        self.client_filter.addItem("")
        self.client_filter.addItem("")
        self.client_log_layout.addWidget(self.client_filter, 0, 1, 1, 1)
        self.client_log = QtWidgets.QTextBrowser(self.client_log_tab)
        self.client_log.setObjectName("client_log")
        self.client_log_layout.addWidget(self.client_log, 1, 0, 1, 2)
        self.log_tabs.addTab(self.client_log_tab, "")
        self.isaac_log_tab = QtWidgets.QWidget()
        self.isaac_log_tab.setObjectName("isaac_log_tab")
        self.isaac_log_layout = QtWidgets.QGridLayout(self.isaac_log_tab)
        self.isaac_log_layout.setContentsMargins(11, 11, 11, 11)
        self.isaac_log_layout.setSpacing(6)
        self.isaac_log_layout.setObjectName("isaac_log_layout")
        self.isaac_filter_label = QtWidgets.QLabel(self.isaac_log_tab)
        self.isaac_filter_label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.isaac_filter_label.setWordWrap(True)
        self.isaac_filter_label.setObjectName("isaac_filter_label")
        self.isaac_log_layout.addWidget(self.isaac_filter_label, 0, 0, 1, 1)
        self.isaac_filter = QtWidgets.QComboBox(self.isaac_log_tab)
        self.isaac_filter.setObjectName("isaac_filter")
        self.isaac_filter.addItem("")
        self.isaac_filter.addItem("")
        self.isaac_filter.addItem("")
        self.isaac_filter.addItem("")
        self.isaac_filter.addItem("")
        self.isaac_filter.addItem("")
        self.isaac_log_layout.addWidget(self.isaac_filter, 0, 1, 1, 1)
        self.isaac_filter_modifier = QtWidgets.QCheckBox(self.isaac_log_tab)
        self.isaac_filter_modifier.setChecked(True)
        self.isaac_filter_modifier.setObjectName("isaac_filter_modifier")
        self.isaac_log_layout.addWidget(self.isaac_filter_modifier, 1, 1, 1, 1)
        self.isaac_log = QtWidgets.QTextBrowser(self.isaac_log_tab)
        self.isaac_log.setObjectName("isaac_log")
        self.isaac_log_layout.addWidget(self.isaac_log, 2, 0, 1, 2)
        self.log_tabs.addTab(self.isaac_log_tab, "")
        self.app_layout.addWidget(self.log_tabs, 0, 0, 1, 1)
        ClientApp.setCentralWidget(self.app_central)
        self.menu_bar = QtWidgets.QMenuBar(ClientApp)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.menu_menu = QtWidgets.QMenu(self.menu_bar)
        self.menu_menu.setObjectName("menu_menu")
        self.menu_help = QtWidgets.QMenu(self.menu_bar)
        self.menu_help.setObjectName("menu_help")
        ClientApp.setMenuBar(self.menu_bar)
        self.menu_quit = QtWidgets.QAction(ClientApp)
        self.menu_quit.setObjectName("menu_quit")
        self.help_about = QtWidgets.QAction(ClientApp)
        self.help_about.setObjectName("help_about")
        self.help_help = QtWidgets.QAction(ClientApp)
        self.help_help.setObjectName("help_help")
        self.help_license = QtWidgets.QAction(ClientApp)
        self.help_license.setShortcut("")
        self.help_license.setObjectName("help_license")
        self.menu_settings = QtWidgets.QAction(ClientApp)
        self.menu_settings.setObjectName("menu_settings")
        self.menu_menu.addAction(self.menu_settings)
        self.menu_menu.addSeparator()
        self.menu_menu.addAction(self.menu_quit)
        self.menu_help.addAction(self.help_help)
        self.menu_help.addAction(self.help_about)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.help_license)
        self.menu_bar.addAction(self.menu_menu.menuAction())
        self.menu_bar.addAction(self.menu_help.menuAction())

        self.retranslateUi(ClientApp)
        self.log_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ClientApp)

    def retranslateUi(self, ClientApp):
        _translate = QtCore.QCoreApplication.translate
        ClientApp.setWindowTitle(_translate("ClientApp", "Decision Descent - Client"))
        self.client_filter_label.setText(_translate("ClientApp", "Filter Level"))
        self.client_filter.setItemText(0, _translate("ClientApp", "Critical"))
        self.client_filter.setItemText(1, _translate("ClientApp", "Error"))
        self.client_filter.setItemText(2, _translate("ClientApp", "Warning"))
        self.client_filter.setItemText(3, _translate("ClientApp", "Info"))
        self.client_filter.setItemText(4, _translate("ClientApp", "Debug"))
        self.client_filter.setItemText(5, _translate("ClientApp", "All"))
        self.log_tabs.setTabText(self.log_tabs.indexOf(self.client_log_tab), _translate("ClientApp", "Client"))
        self.isaac_filter_label.setText(_translate("ClientApp", "Filter Level"))
        self.isaac_filter.setItemText(0, _translate("ClientApp", "Critical"))
        self.isaac_filter.setItemText(1, _translate("ClientApp", "Error"))
        self.isaac_filter.setItemText(2, _translate("ClientApp", "Warning"))
        self.isaac_filter.setItemText(3, _translate("ClientApp", "Info"))
        self.isaac_filter.setItemText(4, _translate("ClientApp", "Debug"))
        self.isaac_filter.setItemText(5, _translate("ClientApp", "All"))
        self.isaac_filter_modifier.setText(_translate("ClientApp", "Only Decision Descent output?"))
        self.log_tabs.setTabText(self.log_tabs.indexOf(self.isaac_log_tab), _translate("ClientApp", "Isaac"))
        self.menu_menu.setTitle(_translate("ClientApp", "Menu"))
        self.menu_help.setTitle(_translate("ClientApp", "Help"))
        self.menu_quit.setText(_translate("ClientApp", "Quit"))
        self.menu_quit.setShortcut(_translate("ClientApp", "Ctrl+Q"))
        self.help_about.setText(_translate("ClientApp", "About"))
        self.help_about.setShortcut(_translate("ClientApp", "Ctrl+A"))
        self.help_help.setText(_translate("ClientApp", "Help"))
        self.help_help.setShortcut(_translate("ClientApp", "Ctrl+H"))
        self.help_license.setText(_translate("ClientApp", "License"))
        self.menu_settings.setText(_translate("ClientApp", "Settings..."))

